openapi: 3.0.0
info:
  version: "1.0.0"
  title: Swagger
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: amir.boussaadia@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:8980/
  - url: 'https://petstore.swagger.io/v2'
paths:
  /item:
    post:
      summary: Add a new cryptoCurrency asset
      operationId: addCryptoCurrencyAsset
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalCryptoCurrency'
      requestBody:
        $ref: '#/components/requestBodies/CryptoCurrency'
components:
  schemas:
    CryptoCurrency:
      type: object
      required:
        - symbol
        - location
        - amount
        - date
      properties:
        symbol:
          $ref: '#/components/schemas/Symbol'
        location:
          type: object
          $ref: '#/components/schemas/Location'
        amount:
          type: integer
          format: int64
        date:
          type: string
          format: date
    GlobalCryptoCurrency:
      type: object
      required:
        - symbol
        - location
        - value
        - date
      properties:
        id:
          type: integer
          format: int64
        symbol:
          $ref: '#/components/schemas/Symbol'
        amount:
          type: integer
          format: int64
        entryDate:
          type: string
          format: date
        location:
          $ref: '#/components/schemas/Location'
        oldMarketValue:
          type: integer
          format: int64
        actualMarketValue:
          type: integer
          format: int64
    Symbol:
      type: string
      enum:
        - BITCOIN
        - ETHERUM
    Location:
      type: string
      enum:
        - HARDWARE_WALLET
        - BITFINEX
        - BISTAMP

  requestBodies:
    CryptoCurrency:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CryptoCurrency'
      description: CryptoCurrency
      required: true