openapi: 3.0.0
info:
  version: "1.0.0"
  title: Swagger
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: amir.boussaadia@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:8980/
  - url: 'https://petstore.swagger.io/v2'
paths:
  /item/{symbol}:
    delete:
      summary: delete cryptoCurrency
      operationId: deleteCryptoCurrency
      parameters:
        - in: path
          name: symbol
          schema:
            $ref: '#/components/schemas/Symbol'
          required: true
          description: Cryptocurrency to delete
      responses:
        '200':
          description: successful operation
    get:
      summary: get cryptoCurrency
      operationId: getCryptoCurrency
      parameters:
        - in: path
          name: symbol
          schema:
            $ref: '#/components/schemas/Symbol'
          required: true
          description: Cryptocurrency to get
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalCryptoCurrency'
  /item:
    get:
      summary: get cryptoCurrencies
      operationId: getCryptoCurrencies
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GlobalCryptoCurrency'
    post:
      summary: Add a new cryptoCurrency asset
      operationId: addCryptoCurrencyAsset
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalCryptoCurrency'
      requestBody:
        $ref: '#/components/requestBodies/CryptoCurrency'
components:
  schemas:
    CryptoCurrency:
      type: object
      required:
        - symbol
        - location
        - amount
      properties:
        symbol:
          $ref: '#/components/schemas/Symbol'
        location:
          type: object
          $ref: '#/components/schemas/Location'
        amount:
          type: number
          format: double
    GlobalCryptoCurrency:
      type: object
      required:
        - id
        - symbol
        - location
        - amount
        - entryDate
        - oldMarketValue
        - actualMarketValue
      properties:
        id:
          type: integer
          format: int64
        symbol:
          $ref: '#/components/schemas/Symbol'
        amount:
          type: number
          format: double
        entryDate:
          type: string
          format: date
        location:
          $ref: '#/components/schemas/Location'
        oldMarketValue:
          type: number
          format: double
        actualMarketValue:
          type: number
          format: double
    Symbol:
      type: string
      enum:
        - BITCOIN
        - ETHEREUM
    Location:
      type: string
      enum:
        - HARDWARE_WALLET
        - BITFINEX
        - BISTAMP

  requestBodies:
    CryptoCurrency:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CryptoCurrency'
      description: CryptoCurrency
      required: true